---
page_title: "circleci_context Data Source - circleci"
subcategory: ""
description: |-
  Fetches information about a CircleCI context, including its restrictions.
---

# circleci_context (Data Source)

Fetches information about a CircleCI context, including its restrictions.

## Example Usage

```terraform
data "circleci_context" "example" {
  id = "00000000-0000-0000-0000-000000000000"
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `id` (String) The ID of the context.

### Read-Only

- `created_at` (String) The timestamp when the context was created.
- `name` (String) The name of the context.
- `restrictions` (Attributes List) The access restrictions for this context. (see [below for nested schema](#nestedatt--restrictions))

<a id="nestedatt--restrictions"></a>
### Nested Schema for `restrictions`

Read-Only:

- `id` (String) The unique identifier of the restriction.
- `name` (String) The name associated with the restriction.
- `project_id` (String) The project ID associated with the restriction.
- `type` (String) The type of restriction.
- `value` (String) The value associated with the restriction type.
