---
page_title: "circleci_pipeline Data Source - circleci"
subcategory: ""
description: |-
  Fetches information about a CircleCI pipeline definition.
---

# circleci_pipeline (Data Source)

Fetches information about a CircleCI pipeline definition.

## Example Usage

```terraform
data "circleci_pipeline" "example" {
  id         = "00000000-0000-0000-0000-000000000000"
  project_id = "00000000-0000-0000-0000-000000000001"
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `id` (String) The ID of the pipeline.
- `project_id` (String) The ID of the project the pipeline belongs to.

### Read-Only

- `checkout_source_provider` (String) The provider for the code checkout source.
- `checkout_source_repo_external_id` (String) The external ID of the repository used for code checkout.
- `checkout_source_repo_full_name` (String) The full name of the repository used for code checkout.
- `config_source_file_path` (String) The path to the pipeline configuration file within the repository.
- `config_source_provider` (String) The provider for the pipeline configuration source.
- `config_source_repo_external_id` (String) The external ID of the repository containing the pipeline configuration.
- `config_source_repo_full_name` (String) The full name of the repository containing the pipeline configuration.
- `created_at` (String) The timestamp when the pipeline was created.
- `description` (String) The description of the pipeline.
- `name` (String) The name of the pipeline.
